export const GET_CUSTOMER_BY_ID_REPOSITORY = Symbol(
  'GET_CUSTOMER_BY_ID_REPOSITORY',
);
export const GET_CUSTOMER_BY_ID_SERVICE = Symbol('GET_CUSTOMER_BY_ID_SERVICE');
export const GET_CUSTOMER_BY_ID_USE_CASE = Symbol(
  'GET_CUSTOMER_BY_ID_USE_CASE',
);
