export const RUN_SEED_REPOSITORY = Symbol('RUN_SEED_REPOSITORY');
export const SEED_RUN_CHECK_REPOSITORY = Symbol('SEED_RUN_CHECK_REPOSITORY');
export const LOAD_DATA_SEED_REPOSITORY = Symbol('LOAD_DATA_SEED_REPOSITORY');

export const SEED_RUN_CHECK_SERVICE = Symbol('SEED_RUN_CHECK_SERVICE');
export const RUN_SEED_SERVICE = Symbol('RUN_SEED_SERVICE');

export const RUN_SEED_USE_CASE = Symbol('RUN_SEED_USE_CASE');
